version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
    nodejs: "16"
  commands:
    - npm install
    - npx typedoc
python:
  install:
    - requirements: docs/requirements.txt
sphinx:
  configuration: docs/source/conf.py
formats:
  - htmlzip