BASE_OPTIONS = {
    "options": {
        "applied_unified_filters": None,
        "appliedProductFilters": "---",
        "article": None,
        "auto_correction_disabled": False,
        "corpus": None,
        "customized_rerank_type": None,
        "domains": None,
        "filters": None,
        "journey_depth": None,
        "page_size": None,
        "price_max": None,
        "price_min": None,
        "query_pin_sigs": None,
        "query": None,
        "redux_normalize_feed": True,
        "request_params": None,
        "rs": None,
        "selected_one_bar_modules": None,
        "seoDrawerEnabled": False,
        "source_id": None,
        "source_module_id": None,
        "source_url": None,
        "top_pin_id": None,
        "top_pin_ids": None,
    },
    "context": {},
}

PINTEREST_BASE_HEADERS = {
    "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:139.0) Gecko/20100101 Firefox/139.0",
    "Accept": "application/json, text/javascript, */*, q=0.01",
    "Accept-Language": "fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3",
    "X-Pinterest-AppState": "active",
    "X-Pinterest-PWS-Handler": "www/search/[scope].js",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin",
}